# Generated by Django 5.2.6 on 2025-10-05 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('cantidad_h', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Horas Presupuestadas')),
                ('situacion', models.CharField(choices=[('ACT', 'Activo'), ('PAU', 'Pausado'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='ACT', max_length=3)),
                ('administradores', models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='proyectos_administrados', to=settings.AUTH_USER_MODEL)),
                ('clientes', models.ManyToManyField(related_name='proyectos', to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField()),
                ('empleado', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proyecto')),
            ],
        ),
    ]
