# Generated by Django 5.2.6 on 2025-10-11 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_proyecto', models.CharField(choices=[('DEV', 'Desarrollador'), ('PM', 'Project Manager'), ('QA', 'QA / Tester'), ('OT', 'Otro')], default='OT', max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': False}, related_name='proyectos_como_empleado', through='gestion.AsignacionProyecto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='asignacionproyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empleado', 'proyecto'), name='uq_asignacion_activa_por_empleado_proyecto'),
        ),
    ]
