# Generated by Django 5.2.6 on 2025-10-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_perfilempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoras',
            name='horas',
            field=models.IntegerField(),
        ),
    ]
