# Generated by Django 5.2.6 on 2026-04-16 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_registrohoras_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_rfc', message='RFC invalido. Debe cumplir el formato oficial (12 o 13 caracteres).', regex='^[A-Z&]{3,4}\\d{6}[A-Z0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El telefono debe tener 10 digitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cantidad_h',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
